/*

 BKG_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : C:\Users\David\Documents\GitHub\nuclearhead\res\tiles\bkg_tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bkg_mapWidth 32
#define bkg_mapHeight 32
#define bkg_mapBank 2

extern unsigned char bkg_map[];

/* End of BKG_MAP.H */
