/*

 GUI_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 3
   Tile set      : C:\Users\David\Documents\GitHub\nuclearhead\res\tiles\gui_tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define gui_mapWidth 20
#define gui_mapHeight 3
#define gui_mapBank 2

extern unsigned char gui_map[];

/* End of GUI_MAP.H */
