/*

 TITLE_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\David\Documents\GitHub\nuclearhead\res\tiles\abc_tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define title_mapWidth 20
#define title_mapHeight 18
#define title_mapBank 2

extern unsigned char title_map[];

/* End of TITLE_MAP.H */
